### PR TITLE
Correctly handle paginated response for twitch user emotes

### LINKED ISSUE #615: Subscriber emotes from some channels don't show when I'm the one using them
**Describe the bug:**
- Emotes from 2 of the 3 channels I am subscribed to remain in text form when I send them, and can't be found in the `Alt`+`e` menu.
- Emotes from these 2 channels show correctly when sent by other people.
- Emotes from these 2 channels show correctly in twitch-tui, when I send them through the twitch.tv chat (see screenshot)

**To Reproduce:**
I don't have reliable steps since it's my specific situation. The best I can suggest is:
1. Be subscribed to at least 2 channels.
2. Attempt to send messages containing the related subscriber emotes: emotes from one channel may remain in text form when sent.
3. Attempt to find the subscriber emotes in the popup menu: emotes from one channel may not be found.

**Expected behavior:**
- I expect emotes to display as images when sent, and to show up in the popup menu when searched.

**Screenshots:**
sshot_2024_06_18_23_25_43

**System:**

- Twitch-tui version: 2.6.11

- Operating System: Linux 6.9.5-arch1-1

- Terminal: kitty 0.35.1

- Shell: bash 5.2.26(1)-release

- config.toml:
```toml
[twitch]
username = "Luky75"
channel = "luky75"
server = "irc.chat.twitch.tv"
token = "redacted"

[terminal]
delay = 30
maximum_messages = 500
verbose = false
first_state = "Dashboard"

[storage]
channels = false
mentions = false

[filters]
enabled = false
reversed = false

[frontend]
show_datetimes = true
datetime_format = "%T"
username_shown = true
palette = "pastel"
title_shown = true
margin = 0
badges = true
theme = "dark"
username_highlight = true
state_tabs = false
cursor_shape = "user"
blinking_cursor = true
inverted_scrolling = false
show_scroll_offset = false
twitch_emotes = true
betterttv_emotes = true
seventv_emotes = false
frankerfacez_emotes = true
favorite_channels = []
recent_channel_count = 5
border_type = "plain"
hide_chat_border = true
right_align_usernames = false
show_unsupported_screen_size = true
```

**Additional context:**
- If this issue is hard to diagnose on your own because you're not subscribed to multiple channels, feel free to ask me to do "technical" stuff. I don't know much about Rust, therefore I'd be happy to have an excuse to get into it.

### PR DESCRIPTION
**Pull request by Nogesma**
Fixes #615

This is a very quick fix, let me know if it works.
I disabled fetching global emotes for twitch as it should now be handled by the `get_user_emotes` part.
If it works correctly I'll do a bit of cleanup before merging.

### CODE REVIEW

**Comment by Xithrius** [comment]
I'll be able to test later today (6 hours or so), thank you very much for the quick PR.

**Review by Xithrius — COMMENTED** [review]
Alright, I've tested it out, and here's what I've found:

- Going to my own channel where I should have access to all emotes shows an empty list in the emote picker.
- Going to someone else's channel shows their emotes, but still no global.
- I am subscribed to one channel, but no emotes from said channel show up in any place.

Although I understand you disabled global fetching from `get_global_emotes`, it doesn't seem to be handled by `get_user_emotes`'s response.

Please let me know if I am misunderstanding any functionality.

**Comment by Nogesma** [comment]
Please make sure your token has the `user:read:emotes` scope.
I think I have a warning in the log file if the query fails because of that.
If that's not it I can try to look into it further tomorrow.

**Review by Xithrius — APPROVED** [review]
Ah yeah I see the warning now. Thought I had generated my token with that scope, seems otherwise. Generated the right token, PR works. Please go ahead and do the cleanup when you can.

**Comment by Nogesma** [comment]
Ah sorry I already did it, it's good to merge.

**Comment by Xithrius** [comment]
Very cool. Thanks!

**Pull request merged**
