### PR TITLE
Add FrankerFacez emotes, refactor emotes downloader

### PR DESCRIPTION
**Pull request by Nogesma**
I've cleaned up the code in emotes/downloader.rs by grouping the code depending on the provider. This adds a bit of code but makes it hopefully easier to understand, and easier to add another emote provider in the future if needed.

### CODE REVIEW

**Comment by Xithrius** [comment]
Sorry for the late replies. I'll be reviewing/testing this in the coming days.

**Review by Xithrius — COMMENTED** [review]
I haven't looked too closely at the code yet, but my testing of this implementation doesn't seem to have any problems as of now.

**Review by Xithrius — APPROVED** [review]
Looks good to me at the moment. There are some conflicts though, so after those are resolved I'll merge.

**Comment by Nogesma** [comment]
All conflicts should be fixed.

**Comment by Xithrius** [comment]
Thank you!

**Pull request merged**
