### PR TITLE
Refactor emote parsing, fix some emote display issues

### PR DESCRIPTION
**Pull request by Nogesma**
While cleaning up my code for the emote picker, I ended up rewriting most of the emote parsing code. 
To avoid making the other PR even bigger, here's a separate one.

Most important bug fixes are the emote overlays that should now be properly centered on top of the base emote, and emotes smaller than the width of 1 terminal cell were not being displayed.

There is a more complete list of fixes in my commits messages.

I also added a bunch of tests for the conversion from &str to vec![Span].

A lot of those additions are from adding tests, so hopefully this is not too large of a PR to review.

Let me know if you find any issues, or need any changes.

### CODE REVIEW

**Comment by Xithrius** [comment]
Just confirming so I don't absolutely nuke your other branch - you'd like to get this merged before #524, yeah?

**Comment by Nogesma** [comment]
Yes, I still need to clean up and split into different commits the other branch.

**Comment by Xithrius** [comment]
I hope to go over this code in the next couple of days.

**Review by Xithrius — APPROVED** [review]
It's been a good chunk of time since I've reviewed stuff like this, but I haven't been able to spot anything out of the ordinary. 

Everything looked normal when running this branch as well.

Thank you once again!

**Pull request merged**
