### PR TITLE
Fix off by one error in hightlight

### PR DESCRIPTION
**Pull request by Nogesma**
It's a quick fix but should work. 
I don't know if it would be more efficient to maybe get the highlights indices after wrapping the message, which is the core of the issue here.
edit: I just realized it would break highlight of words spanning multiple lines so I'm not sure what a better solution would look like.

I couldn't manage to find how to send a message with newlines either with the twitch website or with twt so I just added a test case for it, but maybe @vesdev can confirm this fixes it?

Oh and I reverted the PR completely, which downgrades ahash, let me know if  you want me to update it back.

### CODE REVIEW

**Comment by vesdev** [comment]
I can still reproduce the issue
image

**Comment by Nogesma** [comment]
Hmm, what client are you using that inserts newlines in the message? So I can test this myself.

Also did you make sure the PR was applied?

**Comment by vesdev** [comment]
> Hmm, what client are you using that inserts newlines in the message? So I can test this myself.
> 
> Also did you make sure the PR was applied?

Just twt, there are no newlines. Only line breaks are done by textwrap afaik. And yes the pr is applied

**Comment by Nogesma** [comment]
Ah my bad then I didn't understand the issue right, let me fix this

**Comment by Nogesma** [comment]
This should now be fixed, let me know if it works!

**Comment by vesdev** [comment]
This looks like the correct fix and works 👍
Still doesn't build without updating ahash, but that could be a separate pr

**Comment by Xithrius** [comment]
Ok *this* time I'm pretty sure I tested it properly. I'll update the required dependencies in a new commit.

**Comment by Xithrius** [comment]
available in https://github.com/Xithrius/twitch-tui/releases/tag/v2.6.15

**Pull request merged**
